spring.application.name=crn-server

spring.datasource.url=jdbc:mysql://localhost:3307/thogakade
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=validate
